// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SeleniumtestebayTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void seleniumtestebay() {
    driver.get("https://www.ebay.com/");
    driver.manage().window().setSize(new Dimension(1440, 900));
    driver.findElement(By.id("items_list1")).click();
    driver.findElement(By.id("items_list1")).click();
    {
      WebElement element = driver.findElement(By.id("items_list1"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector("#items_list1 .hl-card-header__header-container")).click();
    driver.findElement(By.id("mainContent")).click();
    driver.findElement(By.cssSelector("#items_list1 .hl-card-header__header-container")).click();
    driver.findElement(By.cssSelector("#items_list1 .hl-card-header__header-container")).click();
    driver.findElement(By.id("s0-0-32-4-0-0[1]-4-match-media-0-ebay-carousel-list")).click();
    driver.findElement(By.id("s0-0-32-4-0-0[1]-4-match-media-0-ebay-carousel-list")).click();
    {
      WebElement element = driver.findElement(By.id("s0-0-32-4-0-0[1]-4-match-media-0-ebay-carousel-list"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("s0-0-32-4-0-0[1]-4-match-media-0-ebay-carousel-list")).click();
    driver.findElement(By.id("s0-0-32-4-0-0[1]-4-match-media-0-ebay-carousel-list")).click();
    driver.findElement(By.id("s0-0-32-4-0-0[1]-4-match-media-0-ebay-carousel-list")).click();
    driver.findElement(By.id("s0-0-32-4-0-0[1]-4-match-media-0-ebay-carousel-list")).click();
    {
      WebElement element = driver.findElement(By.id("s0-0-32-4-0-0[1]-4-match-media-0-ebay-carousel-list"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    js.executeScript("window.scrollTo(0,703)");
    driver.findElement(By.cssSelector("#destinations_list2 .hl-popular-destinations-element:nth-child(4) .hl-image__background")).click();
    driver.close();
  }
}
